backend:
  name: git-gateway
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: routes
    label: routes
    folder: src/routes
    create: true
    fields:
      - name: title
      - name: nav_label
      - name: body